[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[theme]
primaryColor = "#0F172A"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8FAFC"
textColor = "#1E293B"
font = "sans serif"
